
<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container">
    <br>
    <h1 class="mt-5">Bienvenue sur le blog de Jean Forteroche pour suivre les épisodes de <strong>"Billet simple pour l'Alaska"</strong></h1>
  </div>
</main>

<?php $title = 'Mon blog'; ?>

<?php ob_start(); ?>


<?php
while ($data = $posts->fetch())
{
?>
    <div class="news">
        <h3>
            <?= htmlspecialchars($data['title']) ?>
            <em>le : <?= $data['creation_date_fr'] ?></em>
        </h3>
        
        <p>
            <?= mb_substr(nl2br($data['content']), 0, 700, 'utf-8') ?>
            {...}
            <br />
            <div class="suite"><em><a href="index.php?action=post&amp;id=<?= $data['id'] ?>" method="post">Suite</a></em></div>
        </p>
    </div>
<?php
}
$posts->closeCursor();
?>
<?php $content = ob_get_clean(); ?>

<?php require('template.php'); ?>

<footer class="footer mt-auto py-3">
  <div class="container">
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>