<?php 
$title = "Bienvenue sur la partie Administrateur du blog de Jean Forteroche"; ?>

<?php ob_start(); ?>

<section id="createPost">
	<h1>Panneau d'administration</h1>
		<div id="managerBlock">
			<p class="returnLink"></p>
			<div id="updateBlock">
				<h1>Bienvenue sur la partie Administrateur du blog de Jean Forteroche</h1>
				<div class="alert alert-secondary" role="alert"> Commentaires signalés <a href="#" class="alert-link"></a>
				</div>
			
			</div>
		</div>
</section>


<?php $content = ob_get_clean(); ?>

<?php require('template.php'); ?>