<?php 
$title = "Nouveau chapitre"; 
$withTinyMce = true; ?>

<?php ob_start(); ?>

<section id="createPost">
	<h1>Panneau d'administration</h1>
		<div id="managerBlock">
			<div id="updateBlock">
				
				<div class="alert alert-dark" role="alert">Créer un chapitre</div>
				<form action="index.php?action=createPost" method="post">
					<label for="title">Titre : </label>
					<input type="text" name="title" id="title" placeholder="Titre du chapitre" size="60" /><br/>
					<textarea class="tinymce" name="content" rows="20" cols="160"></textarea>
					<input type="submit" value="Valider" />
				</form>
			</div>
		</div>
</section>


<?php $content = ob_get_clean(); ?>

<?php require('template.php'); ?>