<?php 
$title = "Modifier chapitre"; ?>

<?php ob_start(); ?>

<section id="createPost">
		<table class="table table-dark table-striped">
        <thead>
          <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Age</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Giraud</td>
            <td>Pierre</td>
            <td>28</td>
          </tr>
          <tr>
            <td>Durand</td>
            <td>Victor</td>
            <td>26</td>
          </tr>
          <tr>
            <td>Joly</td>
            <td>Julia</td>
            <td>27</td>
          </tr>
        </tbody>
      </table>
</section>


<?php $content = ob_get_clean(); ?>

<?php require('template.php'); ?>